service: agent-status

useDotenv: true

provider:
    name: aws
    runtime: nodejs20.x
    timeout: 60

functions:
    agent-status:
        handler: src/agent.handler
        events:
            - http:
                  path: agentsStatus
                  method: post

custom:
    esbuild:
        bundle: true
        minify: true

plugins:
    - serverless-offline
