on:
  push:
    branches:
    - main
    - feature/*
jobs:
  CI:
    name: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: 'Secret scanning'
      uses: trufflesecurity/trufflehog@v3.73.0
    - uses: actions/setup-node@v4.0.2
      with:
        node-version: '20'
    - name: 'Install dependencies'
      run: npm install
    - name: 'Audit'
      run: npm audit
      continue-on-error: true
    - name: 'Validate Current path'
      run: pwd
    - name: 'List files'
      run: ls
  dev:
    name: deploy dev
    environment: 'dev'
    needs: CI
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.0.2
      with:
        node-version: '20'
    - run: npm install
  prod:
    name: deploy prod
    environment: 'prod'
    needs: dev
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.0.2
      with:
        node-version: '20'
    - run: npm install
