on:
  push:
    branches:
    - main
    - feature/*
jobs:
  CI:
    name: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.0.2
      with:
        node-version: '20'
    - run: npm install
    - run: pwd
    - run: ls
  CD:
    name: deploy
    needs: CI
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.0.2
      with:
        node-version: '20'
    - run: npm install
